[project]
name = 'Sonichain'
description = 'Sonichain is a decentralized story-building game on Stacks where players contribute short voice memos to co-create evolving narrative chains. Rounds determine which contribution becomes canon, and contributors are rewarded with NFTs and an optional bounty pool once the story is sealed.'
authors = ['Samuel X: @Sanuel_Eth']
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'
[contracts.Soni_NFT]
path = 'contracts/Soni_NFT.clar'
clarity_version = 3
epoch = 3.0

[contracts.Soni_NFT_Trait]
path = 'contracts/Soni_NFT_Trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.Sonichain]
path = 'contracts/Sonichain.clar'
clarity_version = 3
epoch = 3.0
depends_on = ['Soni_NFT_Trait', 'Soni_NFT']

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
